/* Copies engine/ into public/engine/ so the legacy static pages can load the
 * exact same modules the Next app imports.
 *
 * This is a generated artifact, not a second source: public/engine/ is
 * gitignored and rebuilt on every dev/build. The whole point of the genome
 * work was removing a hand-maintained duplicate of the layout system (invite.html
 * carried its own divergent copy of every layout rule), so the one thing this
 * must never become is a copy someone edits directly.
 */
import { cp, rm, mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = resolve(root, 'engine');
const dest = resolve(root, 'public', 'engine');

await rm(dest, { recursive: true, force: true });
await mkdir(dest, { recursive: true });
await cp(src, dest, { recursive: true });

await writeFile(
  resolve(dest, 'DO-NOT-EDIT.txt'),
  'Generated by scripts/sync-engine.mjs from /engine on every dev and build.\n' +
  'Edits here are silently destroyed. Change /engine instead.\n'
);

console.log('[kadi] synced engine/ -> public/engine/');
